// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3D27WnuvrxowsX3F1Dxr7TXtiQy2q_tI',
    appId: '1:238679620786:web:7b22ffaa2c4d75a1a11dab',
    messagingSenderId: '238679620786',
    projectId: 'mpepe-3abe9',
    authDomain: 'mpepe-3abe9.firebaseapp.com',
    storageBucket: 'mpepe-3abe9.firebasestorage.app',
    measurementId: 'G-67M1WTKE0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1X7_mw-Jf1mD0S7_CBkDmtzFTbwZDsUo',
    appId: '1:238679620786:android:5372ac335481e545a11dab',
    messagingSenderId: '238679620786',
    projectId: 'mpepe-3abe9',
    storageBucket: 'mpepe-3abe9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM2Mc-yO3IUmzaaJWPgg6eKCV5yXuuCSw',
    appId: '1:238679620786:ios:47a337aa528ec196a11dab',
    messagingSenderId: '238679620786',
    projectId: 'mpepe-3abe9',
    storageBucket: 'mpepe-3abe9.firebasestorage.app',
    iosBundleId: 'com.example.mpesa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM2Mc-yO3IUmzaaJWPgg6eKCV5yXuuCSw',
    appId: '1:238679620786:ios:47a337aa528ec196a11dab',
    messagingSenderId: '238679620786',
    projectId: 'mpepe-3abe9',
    storageBucket: 'mpepe-3abe9.firebasestorage.app',
    iosBundleId: 'com.example.mpesa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3D27WnuvrxowsX3F1Dxr7TXtiQy2q_tI',
    appId: '1:238679620786:web:2f3753fc7870806da11dab',
    messagingSenderId: '238679620786',
    projectId: 'mpepe-3abe9',
    authDomain: 'mpepe-3abe9.firebaseapp.com',
    storageBucket: 'mpepe-3abe9.firebasestorage.app',
    measurementId: 'G-Z298PM1JD5',
  );
}
